package com.grepiu.vp

/**
 * 앱 전반에 걸쳐 사용되는 다국어 문자열 세트.
 */
data class UiStrings(
    val menuPlayer: String,
    val menuLocal: String,
    val menuSmb: String,
    val menuDlna: String,
    val menuLicenses: String,
    val menuSettings: String,
    val openFile: String,
    val smbNetwork: String,
    val fileExplorer: String,
    val connectToServer: String,
    val serverIp: String,
    val user: String,
    val password: String,
    val connectNow: String,
    val disconnect: String,
    val folder: String,
    val videoFile: String,
    val mediaServers: String,
    val dlnaExplorer: String,
    val mediaItem: String,
    val searching: String,
    val searchServers: String,
    val settings: String,
    val language: String,
    val korean: String,
    val english: String,
    val theme: String,
    val lightMode: String,
    val darkMode: String,
    val autoMode: String,
    val appVersion: String,
    val checkForUpdates: String,
    val upToDate: String,
    val savedServers: String,
    val addNew: String,
    val serverNameLabel: String,
    val save: String,
    val noVideo: String,
    val noVideosFound: String,
    val playbackError: String,
    val back: String,
    val close: String,
    val applicationInfo: String
)

val KoreanStrings = UiStrings(
    menuPlayer = "플레이어",
    menuLocal = "로컬 파일",
    menuSmb = "SMB 네트워크",
    menuDlna = "DLNA 서버",
    menuLicenses = "오픈소스 정보",
    menuSettings = "설정",
    openFile = "파일 열기",
    smbNetwork = "SMB 네트워크",
    fileExplorer = "파일 탐색기",
    connectToServer = "서버 연결",
    serverIp = "서버 IP 주소",
    user = "사용자",
    password = "비밀번호",
    connectNow = "연결하기",
    disconnect = "접속 종료",
    folder = "폴더",
    videoFile = "비디오 파일",
    mediaServers = "미디어 서버",
    dlnaExplorer = "DLNA 탐색기",
    mediaItem = "미디어 항목",
    searching = "검색 중...",
    searchServers = "미디어 서버 검색 중...",
    settings = "설정",
    language = "언어 설정",
    korean = "한국어",
    english = "영어 (English)",
    theme = "테마 설정",
    lightMode = "라이트 모드",
    darkMode = "다크 모드",
    autoMode = "시스템 설정 (자동)",
    appVersion = "앱 버전",
    checkForUpdates = "업데이트 확인",
    upToDate = "최신 버전을 사용 중입니다.",
    savedServers = "저장된 서버",
    addNew = "새 서버 추가",
    serverNameLabel = "서버 이름",
    save = "저장",
    noVideo = "선택된 영상 없음",
    noVideosFound = "비디오 파일을 찾을 수 없습니다.",
    playbackError = "재생 오류",
    back = "뒤로",
    close = "닫기",
    applicationInfo = "앱 정보"
)

val EnglishStrings = UiStrings(
    menuPlayer = "Player",
    menuLocal = "Local File",
    menuSmb = "SMB Network",
    menuDlna = "DLNA Server",
    menuLicenses = "Licenses",
    menuSettings = "Settings",
    openFile = "Open File",
    smbNetwork = "SMB Network",
    fileExplorer = "File Explorer",
    connectToServer = "Connect to Server",
    serverIp = "Server IP Address",
    user = "User",
    password = "Password",
    connectNow = "Connect Now",
    disconnect = "Disconnect",
    folder = "Folder",
    videoFile = "Video File",
    mediaServers = "Media Servers",
    dlnaExplorer = "DLNA Explorer",
    mediaItem = "Media Item",
    searching = "Searching...",
    searchServers = "Searching for media servers...",
    settings = "Settings",
    language = "Language",
    korean = "Korean",
    english = "English",
    theme = "Theme",
    lightMode = "Light Mode",
    darkMode = "Dark Mode",
    autoMode = "System Settings (Auto)",
    appVersion = "App Version",
    checkForUpdates = "Check for Updates",
    upToDate = "You are using the latest version.",
    savedServers = "Saved Servers",
    addNew = "Add New",
    serverNameLabel = "Server Name",
    save = "Save",
    noVideo = "No Video Selected",
    noVideosFound = "No videos found",
    playbackError = "Playback Error",
    back = "Back",
    close = "Close",
    applicationInfo = "Application Info"
)
