package com.grepiu.vp

/**
 * 앱 전반에 걸쳐 사용되는 다국어 문자열 세트.
 */
data class UiStrings(
    val menuPlayer: String,
    val menuLocal: String,
    val menuSmb: String,
    val menuDlna: String,
    val menuLicenses: String,
    val menuSettings: String,
    val openFile: String,
    val smbNetwork: String,
    val fileExplorer: String,
    val connectToServer: String,
    val serverIp: String,
    val user: String,
    val password: String,
    val connectNow: String,
    val disconnect: String,
    val folder: String,
    val videoFile: String,
    val mediaServers: String,
    val dlnaExplorer: String,
    val mediaItem: String,
    val searching: String,
    val searchServers: String,
    val settings: String,
    val language: String,
    val korean: String,
    val english: String,
    val theme: String,
    val lightMode: String,
    val darkMode: String,
    val autoMode: String,
    val appVersion: String,
    val checkForUpdates: String,
    val upToDate: String,
    val savedServers: String,
    val addNew: String,
    val serverNameLabel: String,
    val save: String,
    val noVideo: String,
    val noVideosFound: String,
    val playbackError: String,
    val playbackErrorPrefix: String,
    val back: String,
    val close: String,
    val confirm: String,
    val applicationInfo: String,
    val anonymousLogin: String,
    val edit: String,
    val update: String,
    val downloadSpeed: String,
    val bufferedSize: String,
    val heapUsage: String,
    // UI 조작 관련
    val expand: String,
    val collapse: String,
    // 에러 및 상태 관련
    val errorIpRequired: String,
    val errorAuthFailed: String,
    val errorConnectionTimeout: String,
    val errorConnectionError: String,
    val errorEmptyFolder: String,
    // 미디어 정보 관련
    val mediaInfoTitle: String,
    val videoTrack: String,
    val audioTrack: String,
    val networkCache: String,
    val resolution: String,
    val codec: String,
    val frameRate: String,
    val bitrate: String,
    val channels: String,
    val sampleRate: String,
    val unknownFile: String,
    val unknownValue: String,
    // SMB 스캔 관련
    val scanServers: String,
    val scanning: String,
    val scanFound: String
)

val KoreanStrings = UiStrings(
    menuPlayer = "플레이어",
    menuLocal = "로컬 파일",
    menuSmb = "SMB 네트워크",
    menuDlna = "DLNA 서버",
    menuLicenses = "오픈소스 정보",
    menuSettings = "설정",
    openFile = "파일 열기",
    smbNetwork = "SMB 네트워크",
    fileExplorer = "파일 탐색기",
    connectToServer = "서버 연결",
    serverIp = "서버 IP 주소",
    user = "사용자",
    password = "비밀번호",
    connectNow = "연결하기",
    disconnect = "접속 종료",
    folder = "폴더",
    videoFile = "비디오 파일",
    mediaServers = "미디어 서버",
    dlnaExplorer = "DLNA 탐색기",
    mediaItem = "미디어 항목",
    searching = "검색 중...",
    searchServers = "미디어 서버 검색 중...",
    settings = "설정",
    language = "언어 설정",
    korean = "한국어",
    english = "영어 (English)",
    theme = "테마 설정",
    lightMode = "라이트 모드",
    darkMode = "다크 모드",
    autoMode = "시스템 설정 (자동)",
    appVersion = "앱 버전",
    checkForUpdates = "업데이트 확인",
    upToDate = "최신 버전을 사용 중입니다.",
    savedServers = "저장된 서버",
    addNew = "새 서버 추가",
    serverNameLabel = "서버 이름",
    save = "저장",
    noVideo = "선택된 영상 없음",
    noVideosFound = "비디오 파일을 찾을 수 없습니다.",
    playbackError = "재생 오류",
    playbackErrorPrefix = "재생 중 오류가 발생했습니다: ",
    back = "뒤로",
    close = "닫기",
    confirm = "확인",
    applicationInfo = "앱 정보",
    anonymousLogin = "익명 접속",
    edit = "수정",
    update = "수정 완료",
    downloadSpeed = "다운로드 속도",
    bufferedSize = "버퍼링 용량",
    heapUsage = "메모리 사용량",
    expand = "메뉴 펼치기",
    collapse = "메뉴 접기",
    errorIpRequired = "서버 IP 주소가 필요합니다.",
    errorAuthFailed = "인증에 실패했습니다.",
    errorConnectionTimeout = "연결 시간이 초과되었습니다 (30초).",
    errorConnectionError = "연결 오류: ",
    errorEmptyFolder = "연결에 실패했거나 폴더가 비어있습니다.",
    mediaInfoTitle = "미디어 정보",
    videoTrack = "비디오 트랙",
    audioTrack = "오디오 트랙",
    networkCache = "네트워크 및 캐시",
    resolution = "해상도",
    codec = "코덱",
    frameRate = "프레임 레이트",
    bitrate = "비트레이트",
    channels = "채널",
    sampleRate = "샘플 레이트",
    unknownFile = "알 수 없는 파일",
    unknownValue = "알 수 없음",
    scanServers = "주변 서버 찾기",
    scanning = "네트워크 스캔 중...",
    scanFound = "개의 서버를 찾았습니다."
)

val EnglishStrings = UiStrings(
    menuPlayer = "Player",
    menuLocal = "Local File",
    menuSmb = "SMB Network",
    menuDlna = "DLNA Server",
    menuLicenses = "Licenses",
    menuSettings = "Settings",
    openFile = "Open File",
    smbNetwork = "SMB Network",
    fileExplorer = "File Explorer",
    connectToServer = "Connect to Server",
    serverIp = "Server IP Address",
    user = "User",
    password = "Password",
    connectNow = "Connect Now",
    disconnect = "Disconnect",
    folder = "Folder",
    videoFile = "Video File",
    mediaServers = "Media Servers",
    dlnaExplorer = "DLNA Explorer",
    mediaItem = "Media Item",
    searching = "Searching...",
    searchServers = "Searching for media servers...",
    settings = "Settings",
    language = "Language",
    korean = "Korean",
    english = "English",
    theme = "Theme",
    lightMode = "Light Mode",
    darkMode = "Dark Mode",
    autoMode = "System Settings (Auto)",
    appVersion = "App Version",
    checkForUpdates = "Check for Updates",
    upToDate = "You are using the latest version.",
    savedServers = "Saved Servers",
    addNew = "Add New",
    serverNameLabel = "Server Name",
    save = "Save",
    noVideo = "No Video Selected",
    noVideosFound = "No videos found",
    playbackError = "Playback Error",
    playbackErrorPrefix = "An error occurred during playback: ",
    back = "Back",
    close = "Close",
    confirm = "OK",
    applicationInfo = "Application Info",
    anonymousLogin = "Anonymous Login",
    edit = "Edit",
    update = "Update",
    downloadSpeed = "Download Speed",
    bufferedSize = "Buffered Size",
    heapUsage = "Memory Usage",
    expand = "Expand menu",
    collapse = "Collapse menu",
    errorIpRequired = "Server IP Address is required.",
    errorAuthFailed = "Authentication failed.",
    errorConnectionTimeout = "Connection timed out (30s).",
    errorConnectionError = "Connection error: ",
    errorEmptyFolder = "Failed to connect or folder empty.",
    mediaInfoTitle = "Media Information",
    videoTrack = "VIDEO TRACK",
    audioTrack = "AUDIO TRACK",
    networkCache = "NETWORK & CACHE",
    resolution = "Resolution",
    codec = "Codec",
    frameRate = "Frame Rate",
    bitrate = "Bitrate",
    channels = "Channels",
    sampleRate = "Sample Rate",
    unknownFile = "Unknown File",
    unknownValue = "Unknown",
    scanServers = "Scan for Servers",
    scanning = "Scanning network...",
    scanFound = " server(s) found."
)
